###
GET http://localhost:8080/test
#GET http://host.docker.internal:8080/test
#GET http://127.0.0.1:8080/test

> {%
    client.test("Request executed successfully", () => {
        const validateExpression = !!response.status.toString().match(/20\d/)
        client.assert(validateExpression, "Response status is not 2xx")
    })
%}

###
GET http://localhost:8080/test1
#GET http://host.docker.internal:8080/test1
#GET http://127.0.0.1:8080/test1

> {%
    client.test("Request executed successfully", () => {
        const validateExpression = !!response.status.toString().match(/20\d/)
        client.assert(validateExpression, "Response status is not 2xx")
    })
%}